# ===============================
# Stage 1: Build Apache Ranger 2.7.0
# ===============================
FROM maven:3.9.3-eclipse-temurin-8 AS ranger-build

# Install required tools for the build.
RUN apt-get update && apt-get install -y python3 git wget && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /opt/ranger

# Clone the specific release branch
RUN git clone --branch release-ranger-2.7.0 https://github.com/apache/ranger.git .

# Build Ranger Admin and Trino plugin
RUN mvn clean package -P'ranger-admin,ranger-trino-plugin' -DskipTests -Drat.skip=true -Denunciate.skip=true

# Create the version file, as it's required by setup.sh but not generated by the build.
# This assumes the Ranger version is 2.7.0, as per the git branch.
RUN echo "2.7.0" > /opt/ranger/version

# ===============================
# Stage 2: Create a minimal image with artifacts (Not strictly needed for this problem, but let's keep it clean)
# ===============================
FROM busybox:latest as ranger-artifacts

COPY --from=ranger-build /opt/ranger/security-admin/target/*.war /opt/ranger/dist/
COPY --from=ranger-build /opt/ranger/plugin-trino/target/*.jar /opt/ranger/dist/

# ===============================
# Stage 3: Create the final runnable Ranger Admin image
# ===============================
FROM eclipse-temurin:8-jre

# ... (rest of your Dockerfile remains the same)